### ISSUE TITLE
make tasks depend on multiple tasks

### ISSUE THREAD

**Issue by gabriel-v** [hoover/snoop2#14]
right now it won't wait for all of those

**Comment by mgax** [comment]
Now, whenever a dependency is done, the next task is always dispatched, even if not all other dependencies are ready. That's ok, because the task [will detect](https://github.com/hoover/snoop2/blob/fdb00ab485c2b7c48906d507c8c477f2feeb9f8d/snoop/data/tasks.py#L66-L67) this condition, and just return. It will be re-dispatched later when more dependencies are done.
